In [1]:
import cvxpy as cp
import numpy as np
import pandas as pd

## 1.1

## 1.2

In [2]:
x11 = cp.Variable(2, nonneg=True, integer=True)

objective11 = cp.Maximize(x11[0] * 4000 + x11[1] * 3000)
constraints11 = [x11[0] * 2 + x11[1] <= 10, x11[0] + x11[1] <= 8, x11[1] <= 7]
problem11 = cp.Problem(objective11, constraints11)
problem11.solve()

print(f"Optimal value: {problem11.value}")
print(f"x = {x11.value}")

Optimal value: 26000.0
x = [2. 6.]


## 1.3

In [3]:
x1, x2, x3 = (
    cp.Variable(nonneg=True),
    cp.Variable(nonneg=True),
    cp.Variable(nonneg=True),
)
objective13 = cp.Maximize(x1 * 2 + x2 * 3 - x3 * 5)
constraints13 = [x1 + x2 + x3 == 7, x1 * 2 - x2 * 5 + x3 >= 10, x1 + x2 * 3 + x3 <= 12]
problem13 = cp.Problem(objective13, constraints13)
problem13.solve()
print(f"Optimal value: {problem13.value:.3f}")
print(f"x1 = {x1.value:.3f}\nx2 = {x2.value:.3f}\nx3 = {x3.value:.3f}")

Optimal value: 14.571
x1 = 6.429
x2 = 0.571
x3 = 0.000


## 1.4

In [4]:
x14 = cp.Variable((4, 4), nonneg=True, integer=True)
objective14 = cp.Minimize(
    2800 * sum(x14[0:4, 0])
    + 4500 * sum(x14[0:3, 1])
    + 6000 * sum(x14[0:2, 2])
    + 7300 * x14[0, 3]
)
constraints14 = [
    sum(x14[0, :]) >= 15,
    sum(x14[0, 1:]) + sum(x14[1, 0:4]) >= 10,
    sum(x14[0, 2:]) + sum(x14[1, 1:3]) + sum(x14[2, 0:2]) >= 20,
    x14[0, 3] + x14[1, 2] + x14[2, 1] + x14[3, 0] >= 12,
    x14[1, 3] == 0,
    x14[2, 2] == 0,
    x14[2, 3] == 0,
    x14[3, 1] == 0,
    x14[3, 2] == 0,
    x14[3, 3] == 0,
]
problem14 = cp.Problem(objective14, constraints14)
problem14.solve()
print(f"Optimal value: {problem14.value:.0f}")
print(f"x = {np.abs(x14.value)}")

Optimal value: 118400
x = [[ 3.  0.  0. 12.]
 [ 0.  0.  0.  0.]
 [ 8.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


## 1.5

In [6]:
data15 = pd.read_csv("data/data1_5.csv")
data15

,B1,B2,B3,B4,B5,B6,B7,B8,产量
A1,6,2,6,7,4,2,5,9,60.0
A2,4,9,5,3,8,5,8,2,55.0
A3,5,2,1,9,7,4,3,3,51.0
A4,7,6,7,3,9,2,7,1,43.0
A5,2,3,9,5,7,2,6,5,41.0
A6,5,5,2,2,8,1,4,3,52.0
需求量,35,37,22,32,41,32,43,38,NaN


## 1.6