# NumPy 入门

In [1]:
# 导入numpy模块
import numpy as np

## 创建数组

In [2]:
# 创建一维数组
a = np.array([1, 2, 3])
# 查看数组对象
a

array([1, 2, 3])

In [3]:
# 查看整数数组对象类型
a.dtype

dtype('int64')

In [4]:
# 创建二维数组
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 生成2×3的全0数组
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 生成3×4的全1数组
np.ones((3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
# 生成2×3的未初始化数组
np.empty([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# arange方法用于创建给定范围内的数组
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [9]:
# 生成3×2的符合(0,1)均匀分布的随机数数组
np.random.rand(3, 2)

array([[0.64387235, 0.50193411],
       [0.71489601, 0.83701052],
       [0.11701345, 0.01699293]])

In [10]:
# 生成0到2范围内长度为5的数组
np.random.randint(3, size=5)

array([2, 0, 2, 1, 1])

In [11]:
# 生成一组符合标准正态分布的随机数数组
np.random.randn(3)

array([-0.74943662, -0.31596787, -0.94554503])

## 数组切片

In [12]:
# 创建一个一维数组
a = np.arange(10) ** 2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
# 获取数组的第3个元素
a[2]

np.int64(4)

In [14]:
# 获取第2个到第4个数组元素
a[1:4]

array([1, 4, 9])

In [15]:
# 一维数组翻转
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [16]:
# 创建一个多维数组
b = np.random.random((3, 3))
b

array([[0.04612691, 0.02362656, 0.1156818 ],
       [0.34491707, 0.53612952, 0.49451142],
       [0.92638798, 0.90392925, 0.02713821]])

In [17]:
# 获取第2行第3列的数组元素
b[1, 2]

np.float64(0.49451141554057176)

In [18]:
# 获取第2列数据
b[:, 1]

array([0.02362656, 0.53612952, 0.90392925])

In [19]:
# 获取第3列前两行数据
b[:2, 2]

array([0.1156818 , 0.49451142])

## 广播机制

In [20]:
# 创建两个不同的数组
a = np.arange(4)
b = np.array([5, 10, 15, 20])
# 两个数组做减法运算
b - a

array([ 5,  9, 13, 17])

In [21]:
# 数组的逻辑运算
b < 20

array([ True,  True,  True, False])

In [22]:
# 数组求均值和方差
np.mean(b)

np.float64(12.5)

In [23]:
# 数组求方差
np.var(b)

np.float64(31.25)

## 矩阵运算

In [24]:
# 创建两个不同的数组
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
# 矩阵元素乘积
A * B

array([[2, 0],
       [0, 4]])

In [25]:
# 矩阵点乘
A.dot(B)

array([[5, 4],
       [3, 4]])

In [26]:
# 矩阵求逆
np.linalg.inv(A)

array([[ 1., -1.],
       [ 0.,  1.]])

In [27]:
# 矩阵求行列式
np.linalg.det(A)

np.float64(1.0)

In [28]:
# 创建一个3×4的数组
a = np.floor(10 * np.random.random((3, 4)))
a

array([[9., 4., 0., 8.],
       [7., 1., 3., 6.],
       [8., 8., 5., 1.]])

In [29]:
# 查看数组维度
a.shape

(3, 4)

In [30]:
# 数组展平
a.ravel()

array([9., 4., 0., 8., 7., 1., 3., 6., 8., 8., 5., 1.])

In [31]:
# 将数组变换为2×6数组
a.reshape(2, 6)

array([[9., 4., 0., 8., 7., 1.],
       [3., 6., 8., 8., 5., 1.]])

In [32]:
# 求数组的转置
a.T

array([[9., 7., 8.],
       [4., 1., 8.],
       [0., 3., 5.],
       [8., 6., 1.]])

In [33]:
a.T.shape

(4, 3)

## 形式变换

In [34]:
# -1维度表示NumPy会自动计算该维度
a.reshape(3, -1)

array([[9., 4., 0., 8.],
       [7., 1., 3., 6.],
       [8., 8., 5., 1.]])

In [35]:
# 按行合并代码清单1-7中的A数组和B数组
np.hstack((A, B))

array([[1, 1, 2, 0],
       [0, 1, 3, 4]])

In [36]:
# 按列合并A数组和B数组
np.vstack((A, B))

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [37]:
# 创建一个新数组
C = np.arange(16.0).reshape(4, 4)
C

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [38]:
# 按水平方向将数组C切分为两个数组
np.hsplit(C, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [39]:
# 按垂直方向将数组C切分为两个数组
np.vsplit(C, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]